# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180904_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='omics_uuid',
            new_name='sodar_uuid'
        ),
    ]
