# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-21 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fileboxes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projectroles", "0014_update_appsetting_value_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileBox",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="SODAR UUID", unique=True),
                ),
                (
                    "date_frozen",
                    models.DateTimeField(default=fileboxes.models.fourteen_days_in_the_future),
                ),
                (
                    "date_expiry",
                    models.DateTimeField(default=fileboxes.models.twenty_one_days_in_the_future),
                ),
                (
                    "state_meta",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "active (created)"),
                            ("INACTIVE", "inactive (access blocked)"),
                            ("DELETED", "deleted"),
                        ],
                        default="INITIAL",
                        help_text="State in the management system",
                        max_length=32,
                    ),
                ),
                (
                    "state_data",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "active (created)"),
                            ("INACTIVE", "inactive (access blocked)"),
                            ("DELETING", "deleting"),
                            ("DELETED", "deleted"),
                        ],
                        default="INITIAL",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(help_text="File box title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="File box description; optional", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that this file box belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileBoxAccountGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="SODAR UUID", unique=True),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="User name of the account that is granted access", max_length=200
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of the account's owner",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, help_text="Email of the account", max_length=200, null=True
                    ),
                ),
                (
                    "file_box",
                    models.ForeignKey(
                        help_text="The file box that this audit entry belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fileboxes.FileBox",
                    ),
                ),
            ],
            options={"ordering": ("username",),},
        ),
        migrations.CreateModel(
            name="FileBoxAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="SODAR UUID", unique=True),
                ),
                (
                    "action",
                    models.TextField(
                        choices=[
                            ("CREATE", "created"),
                            ("ADD_MEMBER", "member added"),
                            ("REMOVE_MEMBER", "member removed"),
                            ("UPDATE_STATE", "state updated"),
                            ("UPDATE_ATTRS", "attribute(s) updated"),
                            ("FS_APPLY_STATE", "state applied to file system"),
                            ("FS_DATA_REMOVED", "all data removed from file system"),
                        ],
                        help_text="The action that was performed",
                    ),
                ),
                ("message", models.TextField(help_text="The user-readable audit trail message")),
                ("raw_log", models.TextField(blank=True, help_text="Raw text output", null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The actor in this audit trail entry",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_box",
                    models.ForeignKey(
                        help_text="The file box that this audit entry belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fileboxes.FileBox",
                    ),
                ),
            ],
            options={"ordering": ("-date_created",),},
        ),
    ]
