# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-25 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileboxes", "0002_auto_20200422_1055"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filebox",
            options={"ordering": ("-date_created",)},
        ),
    ]
