# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("barcodes", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="barcodesetentry",
            name="barcode_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="barcodes.BarcodeSet",
            ),
        )
    ]
