# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="flowcell",
            options={"ordering": ("-run_date", "sequencing_machine", "run_number", "slot")},
        )
    ]
