# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flowcells", "0004_flowcelltag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flowcelltag", unique_together=set([("flowcell", "user", "name")])
        )
    ]
