# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0006_auto_20181207_0923")]

    operations = [
        migrations.AlterField(
            model_name="laneindexhistogram",
            name="flowcell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="index_histograms",
                to="flowcells.FlowCell",
            ),
        )
    ]
