# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0006_contamination_cctttccc")]

    operations = [
        migrations.AddField(
            model_name="flowcell",
            name="demux_reads",
            field=models.CharField(
                blank=True,
                help_text="Specification of the reads to use for demultiplexing (defaults to planned reads_",
                max_length=200,
                null=True,
            ),
        )
    ]
