# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0007_flowcell_demux_reads")]

    operations = [
        migrations.AddField(
            model_name="laneindexhistogram",
            name="min_index_fraction",
            field=models.FloatField(
                default=0.01,
                help_text="Minimal fraction that an adapter must have to appear in index histogram",
            ),
        )
    ]
