# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0008_laneindexhistogram_min_index_fraction")]

    operations = [
        migrations.AddField(
            model_name="library",
            name="demux_reads",
            field=models.CharField(
                blank=True,
                help_text="Specification of the reads to use for demultiplexing (defaults to planned_reads)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flowcell",
            name="demux_reads",
            field=models.CharField(
                blank=True,
                help_text="Specification of the reads to use for demultiplexing (defaults to planned reads)",
                max_length=200,
                null=True,
            ),
        ),
    ]
