# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 15:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("barcodes", "0001_initial"), ("flowcells", "0008_auto_20181207_1054")]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Object SODAR UUID", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hg19", "human"),
                            ("mm9", "mouse"),
                            ("dm6", "fly"),
                            ("danRer6", "zebrafish"),
                            ("rn11", "rat"),
                            ("ce11", "worm"),
                            ("sacCer3", "yeast"),
                            ("__other__", "other"),
                        ],
                        default="hg19",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("barcode_seq", models.CharField(blank=True, max_length=200, null=True)),
                ("barcode_seq2", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "lane_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            validators=[django.core.validators.MinValueValidator(1)]
                        ),
                        size=None,
                    ),
                ),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="barcodes.BarcodeSetEntry"
                    ),
                ),
                (
                    "barcode2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="barcodes2",
                        to="barcodes.BarcodeSetEntry",
                    ),
                ),
                (
                    "barcode_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="barcodes.BarcodeSet"
                    ),
                ),
                (
                    "barcode_set2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="barcode_sets2",
                        to="barcodes.BarcodeSet",
                    ),
                ),
                (
                    "flow_cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libraries",
                        to="flowcells.FlowCell",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        )
    ]
