# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0010_auto_20181207_1619")]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="barcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="barcodes.BarcodeSetEntry",
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="barcode2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="barcodes2",
                to="barcodes.BarcodeSetEntry",
            ),
        ),
    ]
