# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0011_library_add_rank")]

    operations = [
        migrations.AlterModelOptions(
            name="library", options={"ordering": ["flow_cell", "rank", "name"]}
        )
    ]
