# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 19:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("filesfolders", "0004_update_uuid"), ("flowcells", "0011_auto_20181209_1415")]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Object SODAR UUID", unique=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("draft", "Sent")],
                        default="draft",
                        help_text="Status of the message",
                        max_length=50,
                    ),
                ),
                (
                    "body_format",
                    models.CharField(
                        choices=[("text/plain", "Plain Text"), ("text/markdown", "Markdown")],
                        default="text/plain",
                        help_text="Format of the message body",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Message subject.", max_length=200, null=True
                    ),
                ),
                ("body", models.TextField(help_text="Message body.")),
                (
                    "attachment_folder",
                    models.ForeignKey(
                        help_text="Folder for the attachments, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filesfolders.Folder",
                    ),
                ),
                (
                    "flow_cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="flowcells.FlowCell",
                    ),
                ),
            ],
        )
    ]
