# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0012_auto_20190226_1205")]

    operations = [
        migrations.AddField(
            model_name="library",
            name="project_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        )
    ]
