# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 20:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0013_message_author")]

    operations = [
        migrations.AlterField(
            model_name="message", name="body", field=models.TextField(help_text="Message body")
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(
                blank=True, help_text="Message subject", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=[], size=None
            ),
        ),
    ]
