# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0013_library_project_id")]

    operations = [
        migrations.AddField(
            model_name="flowcell",
            name="create_fastq_for_index_reads",
            field=models.BooleanField(
                default=False, verbose_name="Create FAST files for index reads"
            ),
        ),
        migrations.AddField(
            model_name="flowcell",
            name="mask_short_adapter_reads",
            field=models.IntegerField(
                blank=True, help_text="Optional, Minimal length for adapter reads", null=True
            ),
        ),
        migrations.AddField(
            model_name="flowcell",
            name="minimum_trimmed_read_length",
            field=models.IntegerField(
                blank=True,
                help_text="Optional, remove reads shorter than this length after adapter trimming",
                null=True,
            ),
        ),
    ]
