# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-18 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0014_auto_20190327_1245")]

    operations = [
        migrations.AlterField(
            model_name="flowcell",
            name="rta_version",
            field=models.IntegerField(
                choices=[(1, "RTA v1"), (2, "RTA v2"), (3, "RTA v3"), (0, "other")],
                default=2,
                help_text="Major RTA version, implies bcl2fastq version",
            ),
        )
    ]
