# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 20:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0014_auto_20181209_2128")]

    operations = [
        migrations.AlterModelOptions(name="message", options={"ordering": ("-date_created",)}),
        migrations.AlterField(
            model_name="message",
            name="attachment_folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Folder for the attachments, if any.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filesfolders.Folder",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("sent", "Sent")],
                default="draft",
                help_text="Status of the message",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), blank=True, size=None
            ),
        ),
    ]
