# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0016_auto_20190926_1337")]

    operations = [
        migrations.AddIndex(
            model_name="flowcell",
            index=models.Index(
                fields=["project", "status_sequencing"], name="flowcells_f_project_646598_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowcell",
            index=models.Index(
                fields=["project", "status_conversion"], name="flowcells_f_project_d318bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowcell",
            index=models.Index(
                fields=["project", "status_delivery"], name="flowcells_f_project_9bc0a6_idx"
            ),
        ),
    ]
