# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("flowcells", "0016_auto_20181209_2241")]

    operations = [
        migrations.AlterModelOptions(name="message", options={"ordering": ("date_created",)})
    ]
