# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [("projectroles", "0006_add_remote_projects")]

    operations = [
        migrations.CreateModel(
            name="SequencingMachine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Machine SODAR UUID", unique=True
                    ),
                ),
                (
                    "vendor_id",
                    models.CharField(
                        db_index=True,
                        help_text="Vendor ID of the machine",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(help_text="Short name of the machine", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Short description of the machine. ", null=True
                    ),
                ),
                (
                    "machine_model",
                    models.CharField(
                        choices=[
                            ("iSeq", "iSeq"),
                            ("MiSeq", "MiSeq"),
                            ("MiniSeq", "MiniSeq"),
                            ("NextSeq500", "NextSeq 500"),
                            ("HiSeq1000", "HiSeq 1000"),
                            ("HiSeq1500", "HiSeq 1500"),
                            ("HiSeq2000", "HiSeq 2000"),
                            ("HiSeq3000", "HiSeq 3000"),
                            ("HiSeq4000", "HiSeq 4000"),
                            ("NovaSeq6000", "NovaSeq 6000"),
                            ("other", "Other"),
                        ],
                        help_text="The model of the machine",
                        max_length=100,
                    ),
                ),
                ("slot_count", models.IntegerField(default=1)),
                (
                    "dual_index_workflow",
                    models.CharField(
                        choices=[
                            ("A", "MiSeq, HiSeq 2000/2500, NovaSeq 6000"),
                            ("B", "iSeq, MiniSeq, NextSeq, HiSeq 3000/4000, HiSeq X"),
                        ],
                        default="A",
                        help_text="Workflow to use for dual indexing",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project in which this objects belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
        )
    ]
