# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projectroles", "0006_add_remote_projects"), ("sequencers", "0001_initial")]

    operations = [
        migrations.AlterUniqueTogether(
            name="sequencingmachine", unique_together=set([("project", "vendor_id")])
        )
    ]
