# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sequencers", "0002_auto_20181211_1434")]

    operations = [
        migrations.AlterField(
            model_name="sequencingmachine",
            name="vendor_id",
            field=models.CharField(
                db_index=True, help_text="Vendor ID of the machine", max_length=100
            ),
        )
    ]
