# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sequencers", "0003_auto_20181211_1434")]

    operations = [
        migrations.AlterField(
            model_name="sequencingmachine",
            name="description",
            field=models.TextField(
                blank=True,
                help_text='Brief description of the machine, e.g., "HiSeq 4000 bought in 2015".',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sequencingmachine",
            name="label",
            field=models.CharField(
                help_text='Assign a short name, e.g. "HiSeq #1".', max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sequencingmachine",
            name="slot_count",
            field=models.IntegerField(
                default=1,
                help_text="Maximal number of flow cells in one run, e.g. 1 for NextSeq, 2 for HiSeq 4000",
            ),
        ),
        migrations.AlterField(
            model_name="sequencingmachine",
            name="vendor_id",
            field=models.CharField(
                db_index=True,
                help_text="The vendor (Illumina) assigned ID of your sequencer. E.g., the ID might be something like NB501234 for a NextSeq, or ST-K12345 for a HiSeq.",
                max_length=100,
            ),
        ),
    ]
